name: barcode_scanner
description: A barcode scanner for web.
version: 0.3.0
homepage:

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter  
  js: ^0.6.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.17.0

flutter:
  assets:
    - packages/barcode_scanner/barcode_scanner.js
